use hat;
ALTER TABLE lineorder SET TIFLASH REPLICA 0;
ALTER TABLE date SET TIFLASH REPLICA 0;
ALTER TABLE part SET TIFLASH REPLICA 0;
ALTER TABLE supplier SET TIFLASH REPLICA 0;
ALTER TABLE customer SET TIFLASH REPLICA 0;
ALTER TABLE history SET TIFLASH REPLICA 0;