use hat;
ALTER TABLE lineorder SET TIFLASH REPLICA 1;
ALTER TABLE date SET TIFLASH REPLICA 1;
ALTER TABLE part SET TIFLASH REPLICA 1;
ALTER TABLE supplier SET TIFLASH REPLICA 1;
ALTER TABLE customer SET TIFLASH REPLICA 1;
ALTER TABLE history SET TIFLASH REPLICA 1;
ALTER TABLE freshness SET TIFLASH REPLICA 1;
SET @@tidb_distsql_scan_concurrency = 1;
